package org.csulb.cecs.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import org.hibernate.validator.constraints.NotEmpty;

import com.vaadin.annotations.AutoGenerated;

@Entity
public class Course {
	
	@Id
	@AutoGenerated
	private Long id;
	@NotEmpty(message="Must provide a prefix")
	@Column(name="prefix")
	private String prefix;
	@Column(name="courseno", nullable=false)
	@NotEmpty(message="Must provide course no.")
	private String courseNo;
	@Column(name="activity",nullable=false)
	private String activity;
		
	public String getActivity() {
		return activity;
	}
	public void setActivity(String activity) {
		this.activity = activity;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getPrefix() {
		return prefix;
	}
	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}
	public String getCourseNo() {
		return courseNo;
	}
	public void setCourseNo(String courseNo) {
		this.courseNo = courseNo;
	}	
	
}
